### ISSUE TITLE
java.lang.NoSuchFieldError: SET_NULL_FOR_MISSING_COLUMNS

### ISSUE THREAD

**Issue by sonnguyen-dba** [soumilshah1995/DebeziumFlinkHudiSync#2]
Hi Soumil,
Can you help me this issue?

Warning: Ignoring non-Spark config property: fs.s3a.signing-algorithm
24/07/22 11:18:03 WARN Utils: Your hostname, SonNguyens-MacBook-Pro.local resolves to a loopback address: 127.0.0.1; using 10.152.214.146 instead (on interface en0)
24/07/22 11:18:03 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/apache-spark/3.5.1/libexec/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /Users/sonnguyen/.ivy2/cache
The jars for the packages stored in: /Users/sonnguyen/.ivy2/jars
org.apache.hudi#hudi-spark3.5-bundle_2.12 added as a dependency
org.apache.hadoop#hadoop-aws added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-ae2344c8-4c95-4dd6-abeb-050811213e69;1.0
	confs: [default]
	found org.apache.hudi#hudi-spark3.5-bundle_2.12;0.15.0 in central
	found org.apache.hive#hive-storage-api;2.8.1 in central
	found org.slf4j#slf4j-api;1.7.36 in local-m2-cache
	found org.apache.hadoop#hadoop-aws;3.4.0 in central
	found software.amazon.awssdk#bundle;2.23.19 in central
	found org.wildfly.openssl#wildfly-openssl;1.1.3.Final in central
:: resolution report :: resolve 131ms :: artifacts dl 6ms
	:: modules in use:
	org.apache.hadoop#hadoop-aws;3.4.0 from central in [default]
	org.apache.hive#hive-storage-api;2.8.1 from central in [default]
	org.apache.hudi#hudi-spark3.5-bundle_2.12;0.15.0 from central in [default]
	org.slf4j#slf4j-api;1.7.36 from local-m2-cache in [default]
	org.wildfly.openssl#wildfly-openssl;1.1.3.Final from central in [default]
	software.amazon.awssdk#bundle;2.23.19 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   6   |   0   |   0   |   0   ||   6   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-ae2344c8-4c95-4dd6-abeb-050811213e69
	confs: [default]
	0 artifacts copied, 6 already retrieved (0kB/4ms)
24/07/22 11:18:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/07/22 11:18:03 WARN SchedulerConfGenerator: Job Scheduling Configs will not be in effect as spark.scheduler.mode is not set to FAIR at instantiation time. Continuing without scheduling configs
24/07/22 11:18:04 INFO SparkContext: Running Spark version 3.5.1
24/07/22 11:18:04 INFO SparkContext: OS info Mac OS X, 14.5, aarch64
24/07/22 11:18:04 INFO SparkContext: Java version 17.0.2
24/07/22 11:18:04 INFO ResourceUtils: ==============================================================
24/07/22 11:18:04 INFO ResourceUtils: No custom resources configured for spark.driver.
24/07/22 11:18:04 INFO ResourceUtils: ==============================================================
24/07/22 11:18:04 INFO SparkContext: Submitted application: streamer-processed_orders
24/07/22 11:18:04 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
24/07/22 11:18:04 INFO ResourceProfile: Limiting resource is cpu
24/07/22 11:18:04 INFO ResourceProfileManager: Added ResourceProfile id: 0
24/07/22 11:18:04 INFO SecurityManager: Changing view acls to: sonnguyen
24/07/22 11:18:04 INFO SecurityManager: Changing modify acls to: sonnguyen
24/07/22 11:18:04 INFO SecurityManager: Changing view acls groups to:
24/07/22 11:18:04 INFO SecurityManager: Changing modify acls groups to:
24/07/22 11:18:04 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: sonnguyen; groups with view permissions: EMPTY; users with modify permissions: sonnguyen; groups with modify permissions: EMPTY
24/07/22 11:18:04 INFO deprecation: mapred.output.compression.codec is deprecated. Instead, use mapreduce.output.fileoutputformat.compress.codec
24/07/22 11:18:04 INFO deprecation: mapred.output.compress is deprecated. Instead, use mapreduce.output.fileoutputformat.compress
24/07/22 11:18:04 INFO deprecation: mapred.output.compression.type is deprecated. Instead, use mapreduce.output.fileoutputformat.compress.type
24/07/22 11:18:04 INFO Utils: Successfully started service 'sparkDriver' on port 53358.
24/07/22 11:18:04 INFO SparkEnv: Registering MapOutputTracker
24/07/22 11:18:04 INFO SparkEnv: Registering BlockManagerMaster
24/07/22 11:18:04 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
24/07/22 11:18:04 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
24/07/22 11:18:04 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
24/07/22 11:18:04 INFO DiskBlockManager: Created local directory at /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/blockmgr-c1e5c94a-03bf-494e-81b9-d0fdaf71a4b9
24/07/22 11:18:04 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
24/07/22 11:18:04 INFO SparkEnv: Registering OutputCommitCoordinator
24/07/22 11:18:04 INFO JettyUtils: Start Jetty 0.0.0.0:8090 for SparkUI
24/07/22 11:18:04 INFO Utils: Successfully started service 'SparkUI' on port 8090.
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/Documents/BigData/DebeziumFlinkHudiSync/jar/hudi-extensions-0.1.0-SNAPSHOT-bundled.jar at spark://10.152.214.146:53358/jars/hudi-extensions-0.1.0-SNAPSHOT-bundled.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/Documents/BigData/DebeziumFlinkHudiSync/jar/hudi-java-client-0.14.0.jar at spark://10.152.214.146:53358/jars/hudi-java-client-0.14.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/Documents/BigData/DebeziumFlinkHudiSync/jar/hadoop-common-3.4.0.jar at spark://10.152.214.146:53358/jars/hadoop-common-3.4.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/.ivy2/jars/org.apache.hudi_hudi-spark3.5-bundle_2.12-0.15.0.jar at spark://10.152.214.146:53358/jars/org.apache.hudi_hudi-spark3.5-bundle_2.12-0.15.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.4.0.jar at spark://10.152.214.146:53358/jars/org.apache.hadoop_hadoop-aws-3.4.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/.ivy2/jars/org.apache.hive_hive-storage-api-2.8.1.jar at spark://10.152.214.146:53358/jars/org.apache.hive_hive-storage-api-2.8.1.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/.ivy2/jars/org.slf4j_slf4j-api-1.7.36.jar at spark://10.152.214.146:53358/jars/org.slf4j_slf4j-api-1.7.36.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/.ivy2/jars/software.amazon.awssdk_bundle-2.23.19.jar at spark://10.152.214.146:53358/jars/software.amazon.awssdk_bundle-2.23.19.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:///Users/sonnguyen/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.1.3.Final.jar at spark://10.152.214.146:53358/jars/org.wildfly.openssl_wildfly-openssl-1.1.3.Final.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO SparkContext: Added JAR file:/Users/sonnguyen/Documents/BigData/DebeziumFlinkHudiSync/jar/hudi-utilities-slim-bundle_2.12-0.14.0.jar at spark://10.152.214.146:53358/jars/hudi-utilities-slim-bundle_2.12-0.14.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Executor: Starting executor ID driver on host 10.152.214.146
24/07/22 11:18:04 INFO Executor: OS info Mac OS X, 14.5, aarch64
24/07/22 11:18:04 INFO Executor: Java version 17.0.2
24/07/22 11:18:04 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
24/07/22 11:18:04 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@1e12a5a6 for default.
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/org.wildfly.openssl_wildfly-openssl-1.1.3.Final.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO TransportClientFactory: Successfully created connection to /10.152.214.146:53358 after 13 ms (0 ms spent in bootstraps)
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/org.wildfly.openssl_wildfly-openssl-1.1.3.Final.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp3973152189589948259.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/org.wildfly.openssl_wildfly-openssl-1.1.3.Final.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/org.apache.hive_hive-storage-api-2.8.1.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/org.apache.hive_hive-storage-api-2.8.1.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp7379504160012317091.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/org.apache.hive_hive-storage-api-2.8.1.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/org.slf4j_slf4j-api-1.7.36.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/org.slf4j_slf4j-api-1.7.36.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp5578884064838535962.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/org.slf4j_slf4j-api-1.7.36.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/hudi-utilities-slim-bundle_2.12-0.14.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/hudi-utilities-slim-bundle_2.12-0.14.0.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp10286111247622329404.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/hudi-utilities-slim-bundle_2.12-0.14.0.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/hudi-java-client-0.14.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/hudi-java-client-0.14.0.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp17215720865197264543.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/hudi-java-client-0.14.0.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/org.apache.hudi_hudi-spark3.5-bundle_2.12-0.15.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/org.apache.hudi_hudi-spark3.5-bundle_2.12-0.15.0.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp4292683863378180448.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/org.apache.hudi_hudi-spark3.5-bundle_2.12-0.15.0.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/hadoop-common-3.4.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/hadoop-common-3.4.0.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp1679646515949610221.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/hadoop-common-3.4.0.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/org.apache.hadoop_hadoop-aws-3.4.0.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/org.apache.hadoop_hadoop-aws-3.4.0.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp14240917934273810203.tmp
24/07/22 11:18:04 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/org.apache.hadoop_hadoop-aws-3.4.0.jar to class loader default
24/07/22 11:18:04 INFO Executor: Fetching spark://10.152.214.146:53358/jars/software.amazon.awssdk_bundle-2.23.19.jar with timestamp 1721621884000
24/07/22 11:18:04 INFO Utils: Fetching spark://10.152.214.146:53358/jars/software.amazon.awssdk_bundle-2.23.19.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp9361206097087967432.tmp
24/07/22 11:18:05 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/software.amazon.awssdk_bundle-2.23.19.jar to class loader default
24/07/22 11:18:05 INFO Executor: Fetching spark://10.152.214.146:53358/jars/hudi-extensions-0.1.0-SNAPSHOT-bundled.jar with timestamp 1721621884000
24/07/22 11:18:05 INFO Utils: Fetching spark://10.152.214.146:53358/jars/hudi-extensions-0.1.0-SNAPSHOT-bundled.jar to /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/fetchFileTemp16740764583698042787.tmp
24/07/22 11:18:05 INFO Executor: Adding file:/private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00/userFiles-22c109ea-8428-4111-a0f7-b45b9cc8cdc4/hudi-extensions-0.1.0-SNAPSHOT-bundled.jar to class loader default
24/07/22 11:18:05 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 53409.
24/07/22 11:18:05 INFO NettyBlockTransferService: Server created on 10.152.214.146:53409
24/07/22 11:18:05 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
24/07/22 11:18:06 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.152.214.146, 53409, None)
24/07/22 11:18:06 INFO BlockManagerMasterEndpoint: Registering block manager 10.152.214.146:53409 with 434.4 MiB RAM, BlockManagerId(driver, 10.152.214.146, 53409, None)
24/07/22 11:18:06 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.152.214.146, 53409, None)
24/07/22 11:18:06 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.152.214.146, 53409, None)
24/07/22 11:18:06 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
24/07/22 11:18:06 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
24/07/22 11:18:06 INFO MetricsSystemImpl: s3a-file-system metrics system started
24/07/22 11:18:06 WARN CredentialProviderListFactory: Credentials option fs.s3a.aws.credentials.provider contains AWS v1 SDK entry com.amazonaws.auth.EnvironmentVariableCredentialsProvider; mapping to software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider
24/07/22 11:18:06 WARN ConfigurationHelper: Option fs.s3a.connection.establish.timeout is too low (5,000 ms). Setting to 15,000 ms instead
24/07/22 11:18:06 WARN DFSPropertiesConfiguration: Cannot find HUDI_CONF_DIR, please set it as the dir of hudi-defaults.conf
24/07/22 11:18:06 WARN DFSPropertiesConfiguration: Properties file file:/etc/hudi/conf/hudi-defaults.conf not found. Ignoring to load props file
24/07/22 11:18:06 INFO UtilHelpers: Adding overridden properties to file properties.
24/07/22 11:18:06 INFO SparkContext: SparkContext is stopping with exitCode 0.
24/07/22 11:18:06 INFO SparkUI: Stopped Spark web UI at http://10.152.214.146:8090
24/07/22 11:18:06 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
24/07/22 11:18:06 INFO MemoryStore: MemoryStore cleared
24/07/22 11:18:06 INFO BlockManager: BlockManager stopped
24/07/22 11:18:06 INFO BlockManagerMaster: BlockManagerMaster stopped
24/07/22 11:18:06 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
24/07/22 11:18:06 INFO SparkContext: Successfully stopped SparkContext
Exception in thread "main" java.lang.NoSuchFieldError: SET_NULL_FOR_MISSING_COLUMNS
	at org.apache.hudi.DataSourceWriteOptions$.<init>(DataSourceOptions.scala:543)
	at org.apache.hudi.DataSourceWriteOptions$.<clinit>(DataSourceOptions.scala)
	at org.apache.hudi.DataSourceWriteOptions.RECONCILE_SCHEMA(DataSourceOptions.scala)
	at org.apache.hudi.utilities.streamer.HoodieStreamer.combineProperties(HoodieStreamer.java:177)
	at org.apache.hudi.utilities.streamer.HoodieStreamer.<init>(HoodieStreamer.java:146)
	at org.apache.hudi.utilities.streamer.HoodieStreamer.<init>(HoodieStreamer.java:131)
	at org.apache.hudi.utilities.streamer.HoodieStreamer.main(HoodieStreamer.java:584)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
24/07/22 11:18:06 INFO ShutdownHookManager: Shutdown hook called
24/07/22 11:18:06 INFO ShutdownHookManager: Deleting directory /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-b496a050-1978-4957-8aa8-140bcbb93f22
24/07/22 11:18:06 INFO ShutdownHookManager: Deleting directory /private/var/folders/_g/hrvts6zj7v70qmnc_7sps89h0000gn/T/spark-5d425c7a-239d-4c06-98e1-9fec2695fc00
24/07/22 11:18:08 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
24/07/22 11:18:08 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
24/07/22 11:18:08 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.

Regards,
Son

**Comment by soumilshah1995** [comment]
im not sure im understanding can I have more details such as where are you running these jobs what spark version what config etc
